# Configuration for librarian-puppet. For example:
#
forge "http://forge.puppetlabs.com"
#
#mod "puppetlabs/razor"
# mod "puppetlabs/ntp", "0.0.3"
#
#mod "apt",
#   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"


mod 'puppet-rvm', :git => "git://github.com/blt04/puppet-rvm.git"